defaults:
  - multiclassAP.yaml

additional:
  AUC_per_class: 
    _target_: torchmetrics.AveragePrecision
    task: "multiclass"
    num_classes: ${data.dataset.num_classes}
    average: "none"
    thresholds: null
