name: VIT_EAT
norm_layer: nn.LayerNorm
sampling_rate: 32_000
img_size_x: ${data.dataset.target_length}
img_size_y: 128
patch_size: 16
in_chans: 1
embed_dim: 768
global_pool: cls
mlp_ratio: 4
qkv_bias: True
eps: 1e-6
num_heads: 12
depth: 12
drop_path: 0.1
num_classes: ${data.dataset.num_classes} 
pos_trainable: False
#pretrained_weights_path: /home/lrauch/projects/birdMAE/logs/pretrain_xcm_eat/runs/XCM/EAT/2025-07-20_150856/callback_checkpoints/EAT_XCM_epoch=09.ckpt
pretrained_weights_path: /home/datasets/audiomodels/EAT-base_epoch30_pt.pt
target_length: ${data.dataset.target_length}
mask2d: null
mask_t_prob: 0
mask_f_prob: 0
freeze_backbone: false
mask_mode: null  # 'rand' or 'inv' - inverse block masking is typically better for EAT
ppnet_cfg: 
  num_prototypes: 15
  channels_prototypes: 768
  h_prototypes: 1
  w_prototypes: 1
  num_classes: ${data.dataset.num_classes}
  topk_k: 1
  margin: null
  init_weights: true
  add_on_layers_type: upsample
  incorrect_class_connection: null
  correct_class_connection: 1.0
  bias_last_layer: -2.0
  non_negative_last_layer: true
  embedded_spectrogram_height: null
  last_layer_lr: 4e-4
  prototype_lr: 0.04
  focal_similarity: true
# ppnet: 
#   num_prototypes: 420
#   channels_prototypes: 768
#   h_prototypes: 1
#   w_prototypes: 1
#   num_classes: ${data.dataset.num_classes}
#   topk_k: 1
#   margin: null
#   init_weights: true
#   add_on_layers_type: upsample
#   incorrect_class_connection: null
#   correct_class_connection: 1.0
#   bias_last_layer: -2.0
#   non_negative_last_layer: true
#   embedded_spectrogram_height: null
#   last_layer_lr: 4e-4
#   prototype_lr: 0.04
#   focal_similarity: true