defaults: 
  - override hydra_logging: colorlog
  - override job_logging: colorlog 

job:
  chdir: True
run:
  dir: ${paths.root_dir}/tests/runs/${task_name}/${data.dataset.name}/${module.network.name}/${now:%Y-%m-%d_%H%M%S}