_target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
experiment_name: "test"
run_name: ${task_name}_${data.dataset.name}_${start_time}
tracking_uri: sqlite:////home/lrauch/projects/birdMAE/sslbirds.db
log_model: false
