root_dir: ${oc.env:PROJECT_ROOT}
work_dir: ${hydra:runtime.cwd}

output_dir: ${hydra:runtime.output_dir}

dataset_dir: /data/DCLDE_birdmae
log_dir: /mnt/work/bird2vec/logs_pretrain_audioset_MAE/
model_dir: ${paths.log_dir}/model_checkpoints/
background_dir: /scratch/birdset/background/wav/

