root_dir: ${oc.env:PROJECT_ROOT}
work_dir: ${hydra:runtime.cwd}

#output
output_dir: ${hydra:runtime.output_dir}

dataset_dir: /data/dclde_no_balance
model_dir: ${paths.output_dir}/checkpoints/
log_dir: ${paths.output_dir}/logs/



