# @package _global_
defaults:
  - _self_
  - callbacks: default_ssl
  - data/dataset: DCLDE
  - data/loaders: esc50
  - data/transform: melbank_dclde
  - logger: mlflow
  - hydra: workstation
  - module/network: vit_base_16_dclde
  - module/optimizer: adamw
  - module/scheduler: cosine
  - module/loss: single_label
  - module/metric: DCLDE #change pls
  - paths: workstation
  - trainer: single_gpu
  - experiment: null
  
seed: 59

start_time: ${now:%Y-%m-%d_%H%M%S}
task_name: "finetune_torca"

train: true
test: true
 
